### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by aseyfpour** [streamr-dev/streamr-client-javascript#255]
I was working with Streamr Client 5.3.0-alpha.3 and I find out some feature is missing in the dataunion. 

- It's better to let users set the gas limits for the contract call functions (for example `transportMessage`).
- `withdrawAmountToSigned` is not supported in the client, so users have to call the smart contract or use `withdrawAllToSigned`

**Comment by jtakalai** [comment]
Gas price setting ought to be there for the node.js use; for browser I guess metamask allows setting gas.

Thanks for reporting, I'll make a ticket for passing options to the transactions

**Comment by jtakalai** [comment]
Fixed, will be in the next release probably
